### ISSUE TITLE
[question]: Unblock all sites with one click

### ISSUE THREAD

**Issue by TangoPJ** [sneas/green-blocker#1]
Hello, thank you for this useful extension, I installed it and used for several websites.
Then noticed that - when one site is unblocked, for example for 1 minute, sites in other tabs are also unblocked. Is this expected behavior?

**Comment by sneas** [comment]
Hi Rail, thank you for trying it out. Yes, this is intentional behavior. I saw it as "now it's okay to browse any website for N minutes". As far as I can see, this is not something you have expected. Would you like the extension to allow only a specific website?

**Comment by TangoPJ** [comment]
@sneas Thank you for the answer, I just wanted to clarify this case :) I like using the extension in its current form. But I'll try to make a PR with additional feature to close a specific website, if you don't mind :)
